In [8]:
import numpy as np

In [9]:
np.__version__

'1.16.5'

In [10]:
!pip install numpy

In [9]:
a = np.array([1,2,3,4,5])

In [10]:
a

array([1, 2, 3, 4, 5])

In [12]:
b = np.array((6,7,8))

In [13]:
b

array([6, 7, 8])

In [14]:
type(a), type(b)

(numpy.ndarray, numpy.ndarray)

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [19]:
np.arange(1.0,3.0,0.5)

array([1. , 1.5, 2. , 2.5])

In [20]:
np.arange(1.0,3.0,0.5,dtype='float64')

array([1. , 1.5, 2. , 2.5])

In [24]:
a = np.arange(0.13, 0.16 , step=0.01)
print("沒有包含結束值：", a)
b = np.arange(0.12, 0.16, step=0.01)
print("包含結束值：", b)

沒有包含結束值： [0.13 0.14 0.15]
包含結束值： [0.12 0.13 0.14 0.15 0.16]


In [25]:
np.linspace(2,8,num=5)

array([2. , 3.5, 5. , 6.5, 8. ])

In [28]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[0,0,0]])
print(a)
a.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 0 0]]


(4, 3)

In [31]:
b=np.array([[[0,0,1],[0,1,0],[1,0,0]],
           [[1,1,0],[1,0,1],[0,1,1]]])
print(b)
b.shape

[[[0 0 1]
  [0 1 0]
  [1 0 0]]

 [[1 1 0]
  [1 0 1]
  [0 1 1]]]


(2, 3, 3)

In [32]:
b.ndim

3

In [33]:
b.dtype

dtype('int32')

In [34]:
type(b)

numpy.ndarray

In [36]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [39]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [40]:
np.empty((2,2,2))

array([[[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 6.18570189e-321],
        [2.01589600e-312, 1.02916796e-311]]])

In [41]:
np.empty((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
np.random.rand(2,3)

array([[0.23076273, 0.07463264, 0.56665894],
       [0.7327821 , 0.98945258, 0.88062927]])

In [43]:
np.random.randn(2,3)

array([[-0.67672529, -0.36715323,  0.58636928],
       [-2.23314639,  0.62387315,  0.42437455]])

In [44]:
np.random.random_sample(10)

array([5.80266782e-01, 8.86807821e-01, 1.82387754e-01, 1.57949005e-01,
       4.08123631e-01, 9.22065482e-01, 5.05421318e-01, 9.46260208e-01,
       6.32381706e-01, 7.28696747e-04])

In [45]:
np.random.random(10)

array([0.87478266, 0.31791659, 0.79879245, 0.32066174, 0.41276788,
       0.30047483, 0.0654613 , 0.64332968, 0.68319514, 0.78163129])

In [46]:
np.random.randint(1,10,5)

array([7, 3, 2, 5, 2])

In [47]:
np.random.choice(9,10)

array([7, 5, 7, 1, 0, 0, 6, 7, 7, 1])

In [48]:
np.random.choice(1,2)

array([0, 0])

In [52]:
a=np.linspace(10,100,num=101)
a

array([ 10. ,  10.9,  11.8,  12.7,  13.6,  14.5,  15.4,  16.3,  17.2,
        18.1,  19. ,  19.9,  20.8,  21.7,  22.6,  23.5,  24.4,  25.3,
        26.2,  27.1,  28. ,  28.9,  29.8,  30.7,  31.6,  32.5,  33.4,
        34.3,  35.2,  36.1,  37. ,  37.9,  38.8,  39.7,  40.6,  41.5,
        42.4,  43.3,  44.2,  45.1,  46. ,  46.9,  47.8,  48.7,  49.6,
        50.5,  51.4,  52.3,  53.2,  54.1,  55. ,  55.9,  56.8,  57.7,
        58.6,  59.5,  60.4,  61.3,  62.2,  63.1,  64. ,  64.9,  65.8,
        66.7,  67.6,  68.5,  69.4,  70.3,  71.2,  72.1,  73. ,  73.9,
        74.8,  75.7,  76.6,  77.5,  78.4,  79.3,  80.2,  81.1,  82. ,
        82.9,  83.8,  84.7,  85.6,  86.5,  87.4,  88.3,  89.2,  90.1,
        91. ,  91.9,  92.8,  93.7,  94.6,  95.5,  96.4,  97.3,  98.2,
        99.1, 100. ])

In [53]:
a[2]

11.8

In [63]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [65]:
print(b[0:2,2:4])

[8 9]
